replicaCount: 3

image:
  repository: us-central1-docker.pkg.dev/electric-terra-418118/artemis/artemis
  tag: "2.0.0"

  service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  annotations: 
    ingress.kubernetes.io/ssl-redirect: "false"
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
      acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: dev-artemis.nazik.link
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: dev-artemis-tls
     hosts:
       - dev-artemis.nazik.link

  
  
  
  
  